api_platform:
    title: 'Catering API'
    version: '1.0.0'
    mapping:
        paths:
            - '%kernel.project_dir%/src/ApiResource'
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
