vich_uploader:
  db_driver: orm
  mappings:
    meal_image:
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      uri_prefix: /images/meals
      upload_destination: '%kernel.project_dir%/public/images/meals'
    meal_plan_image:
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      uri_prefix: /images/meal_plans
      upload_destination: '%kernel.project_dir%/public/images/meal_plans'
    restaurant_image:
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      uri_prefix: /images/restaurants
      upload_destination: '%kernel.project_dir%/public/images/restaurants'
