api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/login
    methods: [POST]

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
